baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Jakub Szewczyk blog"
  subtitle    = "A blog for all the front-end develobears in the woods."
  copyright   = "© 2018"

  cover       = "img/Bearground.png"
  description = "A blog for all the front-end develobears in the woods."
  metaDescription = "A blog for all the front-end develobears in the woods."
  googleAnalytics = ""
  customCSS = ["css/index.css"]
  RSSLink = ""

  githubName = "jakubszewczyk"
  twitterName = "develobear1"
  linkedinName = "jakub-szewczyk"
  mediumName = ""

  logo = "img/logo.png"

  showSupport = true

  author = "develobear"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Wrocław, PL"
  authorWebsite = "https://www.thedevelobear.com"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


