baseurl         = "https://www.thedevelobear.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "thedevelobear"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
enableRobotsTXT = true
title           = "The Develobear "

[params]
  title       = "The Develobear - A blog for all the front-end develobears in the woods."
  subtitle    = "A blog for all the front-end develobears in the woods."
  copyright   = "©TheDevelobear 2018"

  cover       = "img/Bearground.png"
  description = "A blog for all the front-end developers in the woods."
  metaDescription = "A blog for all the front-end developers in the woods. It is made to be useful for people who code and design a lot."
  googleAnalytics = "UA-127102661-1"
  customCSS = ["css/index.css"]
  RSSLink = ""

  githubName = "jakubszewczyk"
  twitterName = "thedevelobear"
  linkedinName = "jakub-szewczyk"
  mediumName = ""

  logo = "img/logo.png"

  showSupport = false

  author = "Develobear"
  authorAvatar = "img/Bear-avatar.png"
  authorLocation = "Wrocław, PL"
  authorWebsite = "https://www.thedevelobear.com"
  authorDescription = "Psst.. I'm not really a bear 😮"

  pageNotFoundTitle = "404 - Page not found"
  pageOfflineTitle = "It looks like you're out in the woods. Check back when you have internet access!"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Code"
  url = "/tags/code/"
  weight = 100

[[menu.main]]
  name = "Design"
  url = "/tags/design/"
  weight = 99
