baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Jakub Szewczyk blog"
  subtitle    = "A blog for front-end developers."
  copyright   = "© 2018"

  cover       = "img/Bearground.png"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  githubName = "jakubszewczyk"
  twitterName = "develobear1"
  linkedinName = "eueung"
  mediumName = ""

  logo = "img/logo.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "develobear"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


